name: Update version
run-name: Move ${{ inputs.version_type }} tags to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: tag to move version to
        required: true
      version_type:
        type: choice
        description: update major or minor version
        default: 'both'  # major and minor
        options:
          - both
          - major
          - minor

permissions:
  contents: write  # This is required for adding a tag

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: calculate new version
      id: calculate
      run: |
        echo "major=$(echo ${{ inputs.target }} | cut -d. -f1)" >> $GITHUB_OUTPUT
        echo "minor=$(echo ${{ inputs.target }} | cut -d. -f1,2)" >> $GITHUB_OUTPUT
    - name: Tag major version
      if: ${{ github.event.inputs.version_type == 'both' || github.event.inputs.version_type == 'major' }}
      run: |
        git tag -f ${{ steps.calculate.outputs.major }} ${{ inputs.target }}
        git push origin ${{ steps.calculate.outputs.major }} --force
    - name: Tag minor version
      if: ${{ github.event.inputs.version_type == 'both' || github.event.inputs.version_type == 'minor' }}
      run: | 
        git tag -f ${{ steps.calculate.outputs.minor }} ${{ inputs.target }}
        git push origin ${{ steps.calculate.outputs.minor }} --force
